openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /questions:
    get:
      summary: five questions
      operationId: questionsGet
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Question'
  /checkanswers:
    post:
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CorrectAnswer'
      summary: Verify if the user's answers are correct
      operationId: checkanswersPost
components:
  schemas:
    Question:
      type: object
      description: question from Travia
      properties:
        text:
          type: string
        options:
          items:
            type: string
          type: array
    CorrectAnswer:
      type: object
      description: correct answer
      properties:
        text:
          type: string