openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
servers:
- url: /
paths:
  /questions:
    get:
      operationId: questionsGet
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Question'
                type: array
          description: A successful response
      summary: five questions
      x-accepts: application/json
  /checkanswers:
    post:
      operationId: checkanswersPost
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/CorrectAnswer'
                type: array
          description: A successful response
      summary: Verify if the user's answers are correct
      x-accepts: application/json
components:
  schemas:
    Question:
      description: question from Travia
      example:
        options:
        - options
        - options
        text: text
      properties:
        text:
          type: string
        options:
          items:
            type: string
          type: array
      type: object
    CorrectAnswer:
      description: correct answer
      example:
        text: text
      properties:
        text:
          type: string
      type: object

